### ISSUE TITLE
sudo make 出错: dpkg-buildpackage: 错误: dpkg-source -b . subprocess returned exit status 2

### ISSUE THREAD

**Issue by guyuming76** [ikohara/dpkg-unzip-iconv#1]
(base) guyuming@guyuming-UKylin:~/dpkg-unzip-iconv$ sudo make
cp unzip-6.0-iconv.patch unzip-6.0/debian/patches/
echo unzip-6.0-iconv.patch >> unzip-6.0/debian/patches/series
(cd unzip-6.0; \
debchange -liconv "Apply iconv patch"; \
dpkg-buildpackage -rfakeroot -us -uc)
/bin/sh: 2: debchange: not found
dpkg-buildpackage: info: 源码包 unzip
dpkg-buildpackage: info: 源码版本 6.0-25ubuntu1
dpkg-buildpackage: info: source distribution eoan
dpkg-buildpackage: info: 源码修改者 Steve Langasek <steve.langasek@ubuntu.com>
dpkg-buildpackage: info: 主机架构 amd64
 dpkg-source --before-build .
 debian/rules clean
make[1]: 进入目录“/home/guyuming/dpkg-unzip-iconv/unzip-6.0”
dh clean
   debian/rules override_dh_auto_clean
make[2]: 进入目录“/home/guyuming/dpkg-unzip-iconv/unzip-6.0”
/usr/bin/make -f unix/Makefile clean
make[3]: 进入目录“/home/guyuming/dpkg-unzip-iconv/unzip-6.0”

         This is a Unix-specific target.  (Just so you know.)

( cd bzip2; /usr/bin/make -f Makebz2.iz RM="rm -f" clean )
make[4]: 进入目录“/home/guyuming/dpkg-unzip-iconv/unzip-6.0/bzip2”
rm -f blocksort.o huffman.o crctable.o randtable.o compress.o decompress.o bzlib.o libbz2.a
make[4]: 离开目录“/home/guyuming/dpkg-unzip-iconv/unzip-6.0/bzip2”
rm -f unzip funzip unzipsfx unzip.o crc32.o  crypt.o envargs.o explode.o extract.o fileio.o globals.o inflate.o list.o match.o process.o ttyio.o ubz2err.o unreduce.o unshrink.o zipinfo.o unix.o funzip.o crc32.o  cryptf.o globalsf.o inflatef.o ttyiof.o unzipsfx.o crc32_.o  crypt_.o extract_.o fileio_.o globals_.o inflate_.o match_.o process_.o ttyio_.o ubz2err_.o unix_.o api.o apihelp.o crc_gcc.o \
  crc_sysv.o unzipstb.o crypt_.c extract_.c globals_.c inflate_.c \
  ttyio_.c crc_i386s.s msdos_.c process_.c unix_.c unzipsfx.c
rm -f flags
rm -rf ./IZunzip
make[3]: 离开目录“/home/guyuming/dpkg-unzip-iconv/unzip-6.0”
make[2]: 离开目录“/home/guyuming/dpkg-unzip-iconv/unzip-6.0”
   dh_clean
make[1]: 离开目录“/home/guyuming/dpkg-unzip-iconv/unzip-6.0”
 dpkg-source -b .
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building unzip using existing ./unzip_6.0.orig.tar.gz
dpkg-source: info: using patch list from debian/patches/series
patching file unix/unix.c
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored
patching file unix/unxcfg.h
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored
patching file unzip.c
Hunk #1 FAILED at 327.
Hunk #2 succeeded at 706 (offset 40 lines).
Hunk #3 FAILED at 675.
Hunk #4 FAILED at 804.
Hunk #5 FAILED at 1337.
Hunk #6 FAILED at 1518.
Hunk #7 FAILED at 1593.
6 out of 7 hunks FAILED
patching file unzpriv.h
Hunk #1 FAILED at 3008.
1 out of 1 hunk FAILED
patching file zipinfo.c
Reversed (or previously applied) patch detected!  Skipping patch.
3 out of 3 hunks ignored
dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
dpkg-source: info: if patch 'unzip-6.0-iconv.patch' is correctly applied by quilt, use 'quilt refresh' to update it
dpkg-source: 错误: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/unzip-6.0-iconv.patch/ --reject-file=- < unzip-6.0.orig.5jUamf/debian/patches/unzip-6.0-iconv.patch subprocess returned exit status 1
dpkg-buildpackage: 错误: dpkg-source -b . subprocess returned exit status 2
make: *** [Makefile:9：all] 错误 2

**Comment by ikohara** [comment]
@guyuming76 Hi.
I checked your log and found this:

> dpkg-buildpackage: info: 源码修改者 Steve Langasek steve.langasek@ubuntu.com

So you seem to be using Ubuntu.
But this script supports only Debian "testing" distribuiton.
Sorry.
